name: Update Stream Tokens

on:
  schedule:
    - cron: '0 */2 * * *' # প্রতি ২ ঘণ্টা পর পর রান হবে
  workflow_dispatch: # যাতে আমরা ম্যানুয়ালি রান করতে পারি

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Scraper Script
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_KV_NAMESPACE_ID: ${{ secrets.CF_KV_NAMESPACE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # গিটহাবের নিজস্ব ইন্টারনাল টোকেন
        run: python scraper.py
